app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(y = character(0))
app$setInputs(y = 99)
app$setInputs(x = 0)
app$setInputs(x = character(0))
app$setInputs(x = 0)
app$setInputs(x = character(0))
app$setInputs(x = 8)
app$setInputs(y = 9)
app$setInputs(y = 99)
app$setInputs(y = 9)
app$setInputs(z = 28)
app$setInputs(x = 85)
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(z = 29)
app$setInputs(z = 30)
app$snapshot()
